# html lang
language: en

# main menu navigation
menu:
  Posts: /
  Tags: /tags
  Search: 
  About: /about

copyright:
  name: mao

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# writing
untitled:
  name: Untitled

rss:
  path: atom.xml

utterances:
  enable: true
  repo: maodaisuki/blog
  issueTerm: pathname
  theme: github-light

mathjax:
  enable: true

mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true
  theme: default
  
search:
  path: search.xml
  field: post
  content: true

tag_generator:
  per_page: 0
  # 0 设置为每页不限制数量
  order_by: -date